### PR TITLE
Added missing line of code

### PR DESCRIPTION
**Pull request by JustARatherRidiculouslyLongUsername**
This was there on repl.it, i simply copy pasted it. Guess your 'keeping in sync' technique doesnt work after all huh?

### CODE REVIEW

**Comment by JustARatherRidiculouslyLongUsername** [comment]
Or, you could create a new branch for the chat feature. Your call

**Comment by JustARatherRidiculouslyLongUsername** [comment]
Also just so you know, this makes the game crash entirely

**Comment by rohan-shettyy** [comment]
What makes the game crash entirely, the line of code that was incomplete or the new update?

**Comment by JustARatherRidiculouslyLongUsername** [comment]
The one that was incomplete of course 😛

**Comment by rohan-shettyy** [comment]
Yeah, my bad on that one

**Pull request merged**
